cargo-features = ["edition2024"]

[package]
name = "rpi_player"
version = "0.1.0"
edition = "2024"

[dependencies]
dirs = "5.0"
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
